
clear
Folder = '/data/jux/BBL/projects/pncSingleFuncParcel/scripts/Analysis/Corr_PrincipleGradient_EE_Myelin/PrincipleGradient';
% Convert cifti to gifti format
cmd = ['wb_command -cifti-separate ' Folder '/hcp.gradients.dscalar.nii ' ...
      'COLUMN ' ...
      '-metric CORTEX_LEFT ' Folder '/Gradients.lh.func.gii ' ...
      '-metric CORTEX_RIGHT ' Folder '/Gradients.rh.func.gii'];
system(cmd);
% left hemisphere
cmd = ['wb_command -metric-resample ' Folder '/Gradients.lh.func.gii ' ...
      Folder '/HCP_32k/fs_LR-deformed_to-fsaverage.L.sphere.32k_fs_LR.surf.gii ' ...
      Folder '/fsaverage5/fsaverage5_std_sphere.L.10k_fsavg_L.surf.gii ' ...
      'ADAP_BARY_AREA ' ...
      Folder '/Gradients.lh.fsaverage5.func.gii ' ... 
      '-area-metrics ' ...
      Folder '/HCP_32k/fs_LR.L.midthickness_va_avg.32k_fs_LR.shape.gii ' ...
      Folder '/fsaverage5/fsaverage5.L.midthickness_va_avg.10k_fsavg_L.shape.gii'];
system(cmd);
% Right hemisphere
cmd = ['wb_command -metric-resample ' Folder '/Gradients.rh.func.gii ' ...
      Folder '/HCP_32k/fs_LR-deformed_to-fsaverage.R.sphere.32k_fs_LR.surf.gii ' ...
      Folder '/fsaverage5/fsaverage5_std_sphere.R.10k_fsavg_R.surf.gii ' ...
      'ADAP_BARY_AREA ' ...
      Folder '/Gradients.rh.fsaverage5.func.gii ' ... 
      '-area-metrics ' ...
      Folder '/HCP_32k/fs_LR.R.midthickness_va_avg.32k_fs_LR.shape.gii ' ...
      Folder '/fsaverage5/fsaverage5.R.midthickness_va_avg.10k_fsavg_R.shape.gii'];
system(cmd);

